name: Bonjour
on:
  - push
jobs:
  dire_bonjour:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - name: Read README.md
        id: readme
        uses: juliangruber/read-file-action@v1
        with:
          path: ./README.ms
      - name: print output
        run: |
          echo "${{ steps.readme.outputs.cowsay }}"
